Added users last access to homes
CybertownRevival/ctr pull request #289
Opened 2024-08-15 13:42 UTC by buddysal

Added users last access date to homes and removed the commented section that was a place holder.

2024-08-18 03:11 UTC, smile0711 requested changes

2024-08-18 03:11 UTC, smile0711 commented on api/src/services/member/member.service.ts
> +      lastAccess: member.last_activity,
Normal users will not need this informations, just anyone with admin right for that house. Can we remove this line?

2024-08-18 03:11 UTC, smile0711 commented on spa/src/components/place/home/main2d.vue
> +  watch: {
A watch maybe needed but is the better thing to watch for might be this.$route.params.username

2024-08-20 08:37 UTC, buddysal commented
I updated my PR and fork to the changes you suggested. Hopefully this is more along the lines of how you were talking about doing it. I changed it in a way that hopefully is easier to expand on in future by adding a canStaff area to the member controller, so that can admin and can staff will be their own entity (and prevent possible overlap and wrong access going to wrong things). I also changed the watch to the username instead.

2024-08-25 18:39 UTC, smile0711 approved these changes

2024-08-25 18:39 UTC, merged